### ISSUE TITLE
Scaling of RL policy output

### ISSUE THREAD

**Issue by Batou1406** [Batou1406/dls_orbit_bat_private#12]
# Scaling of RL policy output

The PPO policy output layer consists of 30 dimensions (4 in $[Hz]$, 4 in $[\frac{1}{rad}]$, 12 in $[m]$, 12 in $[N]$).

**Should the different output dimensions be clipped, normalized, offseted or scaled ? If yes, how?**

#### Different possible solutions
- **Clipping** → eg. clip duty cycle to meaningful range ($\in [0,1]$)
- **Offset** One could offset the output so that the learning can be centered around 0. 
- **Scaling** → scale the output such as $f:[-1;1] \to [min, max]$
-  **Min-Max**
- **Z-score**

#### Some GRF metrics

|       | **foot FL (Mean ± Std)** | **foot FR (Mean ± Std)** | **foot RL (Mean ± Std)** | **foot RR (Mean ± Std)** |
|--------|------------------------|-------------------------|-------------------------|-------------------------|
| **x** |   2.52  ±   1.34     |   0.30  ±   0.71      |  -0.24  ±   0.79      |   1.18  ±   0.78      |
| **y** |   1.99  ±   1.01     |   2.99  ±   1.30      |   2.02  ±   1.08      |   3.94  ±   1.28      |
| **z** | 90.46  ± 32.10     | 98.33  ± 29.16      | 91.49  ± 30.84      | 98.25  ± 29.73      |

**Comment by giulioturrisi** [comment]
for the GRF, I think z can be considered as a delta over mass*acc/num_legs_in_stance. In any case, I think that scaling is in general a good idea.

**Comment by Batou1406** [comment]
### Network default scaling 
By default, the network output actions with :
- **mean=0**
- **std=1**

#### Distribution of action of a untrained network
![action_distribution_1](https://github.com/Batou1406/dls_orbit_bat_private/assets/55761147/df4d93e0-a363-452f-a209-6debce7f85ce)
