### ISSUE TITLE
Center the foot touch down position around the hip position at take-off

### ISSUE THREAD

**Issue by Batou1406** [Batou1406/dls_orbit_bat_private#13]
# Center the foot touch down position around the hip position at take-off

#### Context
Now, the foot touch down position $p$, outputed by the RL policy, is centered around the hip position. This means, if the hip moves, the foot touch down position also, which means, the RL policy must adapt to that and try to continuously follow the hip position, which makes the task hard.
A example of this behaviour can be seen in this video : 
https://github.com/Batou1406/dls_orbit_bat_private/assets/55761147/532d328c-bc92-486d-99e0-ce46e22a4f66

#### Proposition
Instead, of continuously center around the hip, it could be beneficial to center around the hip position at lift-off (and save that position).

**Comment by giulioturrisi** [comment]
That's tricky. Usually real robot will drift, and the position at lift off in the world frame is not anymore a so good initial point. Usually, from a model-based perspective, we always choose a hip-centric stepping type. The foot pos is a delta around the hip that is 0,0, whatever, right?

**Comment by Batou1406** [comment]
Yes, the foot touch-down position $p$ is a delta around the hip. Which mean the foot touch-down position $p$ is (0,0), if it is right under the hip. 

Will the real robot position drift significantly in a single step ?

Because now, the if the foot touch-down position variable is kept constant $p=(0,0)$, but the robot (thus the hip) is moving forward, the "real" touch down position will also move forward (to be kept under the hip). I would thus suggest to center it with respect to the hip position **at lift-off**. I would not expect that to drift significantly in a single step or am I wrong ?

**Comment by Batou1406** [comment]
Implemented, discussed with Giulio, and agreed
